### ISSUE TITLE
Github shows: it's made in D

### ISSUE THREAD

**Issue by tripulse** [DeflatedPickle/blame#7]
Seems, kinda suspicious, isn't it? :thinking:
![image](https://user-images.githubusercontent.com/37257726/83213927-054ce500-a181-11ea-99f8-a18e8a2362f6.png)

**Comment by DeflatedPickle** [comment]
I wasn't aware there was activity here, sorry about that. It's labeled as D as I experimented with rewriting the library in D. I replaced the main branch with the D rewrite when I decided to do the rewrite. Upon next commit, this caused GitHub to index it as D. But I since switched the main branch back to the more stable (and more complete) C++ branch but never committed to it, so it hasn't been indexed since by GitHub

**Comment by tripulse** [comment]
Wow, you replied nearly a year later and I'm not even in r/PH.

**Comment by DeflatedPickle** [comment]
Dang, I could have left it a whole year if only I checked the date! Would've been some premium™ grade support
